### ISSUE TITLE
Hello,could you please upload a realease version so that i can have a try ? Because my devlopment environment have not VS2017 and it's too heavy to me.

### ISSUE THREAD

**Issue by 245432007** [re-esper/rsign#1]
Anyway,thanks for your share.

**Comment by re-esper** [comment]
我上传了个在bin\rsign
应该是在CentOS 7.6下跑过

**Comment by 245432007** [comment]
> 我上传了个在bin\rsign
> 应该是在CentOS 7.6下跑过
哦哦，谢谢，我试试

**Comment by 245432007** [comment]
> 我上传了个在bin\rsign
> 应该是在CentOS 7.6下跑过

我这期间也有发现另外一个github项目可以在linux进行ios12的重签名，zsign。

**Comment by re-esper** [comment]
额, 我做的时候还找不到任何支持iOS12的签名工具, 他上传时间比我晚了2天
